
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw
      when: ansible_nodename == "kub-master"
 

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"
      when: ansible_nodename == "kub-master"


    - name: join cluster
      shell: "{{ hostvars['master'].join_command }} >> node_joined.txt"
      args:
#        chdir: $HOME
        creates: node_joined.txt
      when: ansible_nodename == "kub-node"  
      
    - name: join cluster
      shell: "{{ hostvars['master'].join_command }} >> node_joined.txt"
      args:
#        chdir: $HOME
        creates: node_joined.txt
      when: ansible_nodename == "kub-node2"
       
